#!/usr/bin/env python3
"""Embed the canonical Metal source without runtime filesystem dependencies."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
source=(root/'PsychMetalShaders.metal').read_text()
text='// Generated by tests/embed_shaders.py; do not edit.\nstatic const char PMMetalSource[] =\n'+ '\n'.join(json.dumps(line) for line in source.splitlines(keepends=True))+';\n'
path=root/'PsychMetalShaders.h'
if not path.exists() or path.read_text()!=text:path.write_text(text)
